version: '3.8'

services:
  web-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-scraper
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
    security_opt:
      - seccomp=chrome.json
    cap_add:
      - SYS_ADMIN
    # Additional settings for better performance
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G